# Generated by Django 4.1.1 on 2022-09-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='use_in_slider',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=12, verbose_name='Цена'),
        ),
    ]
